# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the al_eth network device driver.
#

obj-$(CONFIG_AL_ETHERNET) += al_eth.o

al_eth-y := al_eth_ec.o al_eth_mac.o al_eth_main.o al_eth_mdio.o \
            al_eth_netdev.o al_eth_tx.o
